services:
  multistore-checker:
    image: ghcr.io/terrorsource/multistore-checker:latest
    container_name: multistore-checker
    restart: unless-stopped
    network_mode: bridge
    environment:
      - TZ=Europe/Amsterdam
      - PUID=1000
      - PGID=1000
    ports:
      - "9060:8000"
    volumes:
      - /share/CACHEDEV1_DATA/Docker/multistore-checker:/config
